version: '3.9'
services:
  web:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: web
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ../src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - default

networks:
  default:
    driver: bridge
